/*
 * This source file was generated by the Gradle 'init' task
 */
package org.dkedu

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {

    }
}
